- .gitignore
- db/models.js
- db/schema.sql
- package.json
- routes.js
- server.js
- serverConfig.js
- util/requestHandler.js
Add schema for mysql.
Implement express server and create basic functionality files for server.
Closes #5, #2
> Set up database and server skeleton

- tiny-task-app/src/app/app.component.spec.ts
- tiny-task-app/src/app/nav/nav.component.spec.ts
Import components to app spec test.
Write test to check initial nav-bar state.
> Implement basic test for app and nav components

- tiny-task-app/src/app/app.component.html
- tiny-task-app/src/app/app.component.ts
- tiny-task-app/src/app/app.module.ts
- tiny-task-app/src/app/projects/Project.ts
- tiny-task-app/src/app/projects/project-details/Task.ts
- tiny-task-app/src/app/projects/project-details/phases/Phase.ts
- tiny-task-app/src/app/projects/projects.component.ts
- tiny-task-app/src/app/services/nav-service/nav.service.spec.ts
- tiny-task-app/src/app/services/nav-service/nav.service.ts
- tiny-task-app/src/app/services/projects-service/projects.service.ts
- tiny-task-app/src/app/services/user-service/user.service.ts
- tiny-task-app/src/app/user-info/user-info.component.html
- tiny-task-app/src/app/user-info/user-info.component.ts
Add functions for GET and POST requests for projects and users in their respective services.
> Implement HTTP requesting from Project & User services

- tiny-task-app/src/app/app.component.html
- tiny-task-app/src/app/material-modules/material.module.ts
- tiny-task-app/src/app/projects/project-details/project-details.component.html
- tiny-task-app/src/app/projects/projects.component.css
- tiny-task-app/src/app/projects/projects.component.html
- tiny-task-app/src/app/router-modules/app-router.module.ts
Add Route for /project/:id.
Add dropdown menu for project component.
Add rough draft for project details component.
> Implemented routes for specific projects and add additional styles

- tiny-task-app/src/app/projects/project-details/phases/phases.component.ts
- tiny-task-app/src/app/projects/project-details/project-details.component.ts
- tiny-task-app/src/app/projects/projects.component.ts
- tiny-task-app/src/app/services/projects-service/projects.service.ts
- tiny-task-app/src/app/services/user-service/user.service.ts
- tiny-task-app/src/app/user-info/user-info.component.ts
Render phases for a specific project using mock data.
Closes #39
> Implement phase component functionality

- tiny-task-app/src/app/app.component.css
- tiny-task-app/src/app/projects/project-details/project-details.component.css
- tiny-task-app/src/app/projects/project-details/project-details.component.html
- tiny-task-app/src/app/projects/projects.component.css
- tiny-task-app/src/app/projects/projects.component.html
- tiny-task-app/src/styles.css
> Add styles and html elements for project details component

- tiny-task-app/src/app/projects/project-details/project-details.component.html
- tiny-task-app/src/app/projects/project-details/project-details.component.ts
- tiny-task-app/src/app/projects/project-details/project-user/User.ts
- tiny-task-app/src/app/projects/project-details/project-user/project-user.component.ts
- tiny-task-app/src/app/services/team-service/team.service.ts
- tiny-task-app/src/app/services/user-service/user.service.ts
Create functionality for Project-Detail component to fetch project-user data.
Connect Project-Users component to Project-Details component for rendering based on data.
Closes #43
> Render Project-Users components from project-detail component data

- tiny-task-app/src/app/app.component.html
- tiny-task-app/src/app/app.component.ts
- tiny-task-app/src/app/projects/project-details/project-details.component.ts
- tiny-task-app/src/app/projects/projects.component.html
- tiny-task-app/src/app/projects/projects.component.ts
- tiny-task-app/src/app/services/user-service/user.service.ts
- tiny-task-app/src/app/teams/Team.ts
Allow navigation bar to render based on nav service when clicking to different pages/views.
> Adjust navigation render logic through nav service

- tiny-task-app/src/app/projects/project-details/phases/phases.component.html
- tiny-task-app/src/app/projects/project-details/project-details.component.html
- tiny-task-app/src/app/projects/project-details/project-details.component.ts
- tiny-task-app/src/app/projects/project-details/project-user/project-user.component.html
- tiny-task-app/src/app/services/projects-service/projects.service.ts
- tiny-task-app/src/app/services/team-service/team.service.ts
- tiny-task-app/src/app/services/user-service/user.service.ts
Create mock data for project member adding.
Render project members when clicking on project and adding project members.
> Add functionality for adding project members with mock data

- tiny-task-app/src/app/app.component.html
- tiny-task-app/src/app/app.module.ts
- tiny-task-app/src/app/projects/project-details/project-details.component.html
- tiny-task-app/src/app/projects/project-details/project-details.component.ts
- tiny-task-app/src/app/projects/projects.component.html
- tiny-task-app/src/app/projects/projects.component.ts
- tiny-task-app/src/app/router-modules/app-router.module.ts
- tiny-task-app/src/app/services/projects-service/projects.service.ts
- tiny-task-app/src/app/services/user-service/user.service.ts
- tiny-task-app/src/app/teams/teams.component.html
- tiny-task-app/src/app/teams/teams.component.spec.ts
- tiny-task-app/src/app/teams/teams.component.ts
- tiny-task-app/src/app/user-info/user-info.component.html
- tiny-task-app/src/app/user-info/user-info.component.ts
Change Projects, ProjectDetails, UserInfo, and Phases components to not store data on component, but use data from shared Projects and Users services.
> Reformat component states into shared-service state/data 

- seed.js
- tiny-task-app/src/app/projects/project-details/phases/phases.component.css
- tiny-task-app/src/app/projects/project-details/phases/phases.component.html
- tiny-task-app/src/app/projects/project-details/phases/phases.component.ts
- tiny-task-app/src/app/projects/project-details/phases/tasks/tasks.component.html
- tiny-task-app/src/app/projects/project-details/phases/tasks/tasks.component.ts
- tiny-task-app/src/app/projects/project-details/project-details.component.html
- tiny-task-app/src/app/projects/project-details/project-details.component.ts
- tiny-task-app/src/app/projects/project-details/project-user/User.ts
- tiny-task-app/src/app/projects/projects.component.ts
- tiny-task-app/src/app/services/projects-service/projects.service.ts
- tiny-task-app/src/app/services/user-service/user.service.ts
- tiny-task-app/src/app/user-info/user-info.component.html
- tiny-task-app/src/app/user-info/user-info.component.ts
Connect Projects and Project Details components with backend routes.
Closes #74, #49
> Add functionalities for Phase and Task components

- tiny-task-app/src/app/projects/Project.ts
- tiny-task-app/src/app/projects/projects.component.ts
- tiny-task-app/src/app/services/projects-service/projects.service.ts
- tiny-task-app/src/app/services/user-service/user.service.ts
- tiny-task-app/src/app/user-info/user-info.component.ts
- util/requestHandler.js
Change data sent from backend to frontend for correct usage.
> Correct data sent from backend to project components

- tiny-task-app/src/app/projects/project-details/phases/phases.component.ts
- tiny-task-app/src/app/services/projects-service/projects.service.ts
- util/helperFunctions.js
Change API endpoint routes to handle correct data being sent from the frontend.
> Connect phase adding, editing, and removing to backend routes.

- tiny-task-app/src/app/app.component.html
- tiny-task-app/src/app/app.module.ts
- tiny-task-app/src/app/page-not-found/page-not-found.component.html
- tiny-task-app/src/app/page-not-found/page-not-found.component.spec.ts
- tiny-task-app/src/app/page-not-found/page-not-found.component.ts
- tiny-task-app/src/app/projects/projects.component.ts
- tiny-task-app/src/app/router-modules/app-router.module.ts
- tiny-task-app/src/app/services/projects-service/projects.service.ts
- tiny-task-app/src/app/services/team-service/team.service.ts
- tiny-task-app/src/app/services/user-service/user.service.ts
- tiny-task-app/src/app/teams/team-details/team-details.component.html
- tiny-task-app/src/app/teams/team-details/team-details.component.spec.ts
- tiny-task-app/src/app/teams/team-details/team-details.component.ts
- tiny-task-app/src/app/teams/teams.component.html
- tiny-task-app/src/app/teams/teams.component.ts
- tiny-task-app/src/app/user-info/user-info.component.ts
Add component rendering for page not found and teams.
Update Teams service with HTTP request functionality.
> Implement Teams component routing and PageNotFound component

- tiny-task-app/src/app/app.component.css
- tiny-task-app/src/app/app.module.ts
- tiny-task-app/src/app/projects/project-details/phases/phases.component.html
- tiny-task-app/src/app/projects/project-details/phases/phases.component.ts
- tiny-task-app/src/app/projects/project-details/project-details.component.html
- tiny-task-app/src/app/projects/project-details/project-details.component.ts
- tiny-task-app/src/app/projects/project-details/project-user/project-user.component.css
- tiny-task-app/src/app/projects/project-details/project-user/project-user.component.html
- tiny-task-app/src/app/projects/project-details/project-user/project-user.component.ts
- tiny-task-app/src/app/projects/projects.component.html
- tiny-task-app/src/app/projects/projects.component.ts
- tiny-task-app/src/app/services/projects-service/projects.service.ts
- tiny-task-app/src/app/services/team-service/team.service.ts
- tiny-task-app/src/app/teams/Team.ts
- tiny-task-app/src/app/teams/team-details/team-details.component.css
- tiny-task-app/src/app/teams/team-details/team-details.component.html
- tiny-task-app/src/app/teams/team-details/team-details.component.ts
- tiny-task-app/src/app/teams/teams.component.css
- tiny-task-app/src/app/teams/teams.component.html
- tiny-task-app/src/app/teams/teams.component.ts
- tiny-task-app/src/styles.css
- util/helperFunctions.js
- util/requestHandler.js
Add functionality to TeamDetails component for showing members, deleting members, and re-routing to new page for member.
Change ProjectDetails component to render live data for project members.
Closes #114
> Implement Team Details Component and modify ProjectDetails

- tiny-task-app/src/app/projects/project-details/project-details.component.html
- tiny-task-app/src/app/projects/project-details/project-user/project-user.component.html
- tiny-task-app/src/app/projects/project-details/project-user/project-user.component.ts
Render Project-User conditionally if viewed from TeamDetails or ProjectDetails.
> Add conditional rendering of Project-User

- tiny-task-app/src/app/app.component.css
- tiny-task-app/src/app/app.component.html
- tiny-task-app/src/app/projects/project-details/project-details.component.html
- tiny-task-app/src/app/services/projects-service/projects.service.ts
- tiny-task-app/src/app/user-info/user-info.component.css
- tiny-task-app/src/app/user-info/user-info.component.html
- tiny-task-app/src/styles.css
- util/requestHandlers/projects.js
Fix bug on reorderPhases in requestHandlers projects.js
Fix bug on delete confirm for projects
> Update user component style and nav bar

- routes.js
- tiny-task-app/src/app/services/team-service/team.service.ts
- tiny-task-app/src/app/teams/team-details/team-details.component.html
- tiny-task-app/src/app/teams/team-details/team-details.component.ts
- util/requestHandlers/teams.js
- util/requestHandlers/users.js
Render TeamDetails component with adding of members.
Fix bug for user with no team.
> Feature: Team Member Adding

- db/models.js
- routes.js
- seed.js
- util/requestHandlers/announcements.js
- util/requestHandlers/projects.js
- util/requestHandlers/users.js
/projects/teams/:team_id returns all project ids associated with that team,
/users/projects/:user_id returns just project ids associated with that user
> Add two new routes 

- tiny-task-app/src/app/projects/project-details/project-details.component.ts
- tiny-task-app/src/app/projects/projects.component.html
- tiny-task-app/src/app/projects/projects.component.ts
- tiny-task-app/src/app/services/projects-service/projects.service.ts
- tiny-task-app/src/app/services/user-service/user.service.ts
- tiny-task-app/src/app/teams/team-details/team-details.component.html
- tiny-task-app/src/app/teams/team-details/team-details.component.ts
- tiny-task-app/src/app/teams/teams.component.ts
- tiny-task-app/src/app/user-info/user-info.component.ts
Projects can now be sorted and shown by teams via a dropdown select.
Fix async loading issues for projects and teams.
> Feature: Team Sorting

- tiny-task-app/src/app/projects/project-details/phases/phases.component.html
- tiny-task-app/src/app/projects/project-details/phases/phases.component.ts
- tiny-task-app/src/app/projects/projects.component.ts
- tiny-task-app/src/app/services/nav-service/nav.service.ts
- tiny-task-app/src/app/services/projects-service/projects.service.ts
- tiny-task-app/src/app/services/team-service/team.service.ts
- tiny-task-app/src/app/services/user-service/user.service.ts
- tiny-task-app/src/app/teams/team-details/team-members/team-members.component.css
- tiny-task-app/src/app/teams/team-details/team-members/team-members.component.html
- tiny-task-app/src/app/teams/team-details/team-members/team-members.component.ts
- util/helpers/tasks.js
- util/requestHandlers/users.js
> Implement assign user tasks, TeamMembers component, and UX fixes

- routes.js
- tiny-task-app/src/app/projects/project-details/project-user/project-user.component.html
- tiny-task-app/src/app/projects/project-details/project-user/project-user.component.ts
- tiny-task-app/src/app/projects/projects.component.html
- tiny-task-app/src/app/projects/projects.component.ts
- tiny-task-app/src/app/router-modules/app-router.module.ts
- tiny-task-app/src/app/services/projects-service/projects.service.ts
- tiny-task-app/src/app/services/team-service/team.service.ts
- tiny-task-app/src/app/services/user-service/user.service.ts
- tiny-task-app/src/app/teams/team-details/team-details.component.ts
- tiny-task-app/src/app/teams/team-details/team-members/team-members.component.html
- tiny-task-app/src/app/teams/team-details/team-members/team-members.component.ts
- util/helpers/tasks.js
- util/helpers/users.js
- util/requestHandlers/projects.js
- util/requestHandlers/users.js
> Team User Projects components, UX fixes

- src/app/services/team-service/team.service.ts
- src/app/teams/team-details/team-details.component.ts
Save Nav service lastVisited to selected team from Team component.
> Change stored team to selected team from Teams component for better UX

- src/app/services/user-service/user.service.ts
- src/app/user-info/user-info.component.html
- src/app/user-info/user-info.component.ts
Add User service functions and user info components functions for changing a user's availability.
> Implement user availability changer
